import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          ABANDON ALL HOPE
        </p>
        <p>THERE IS ONLY MEANINGLESS MISERY</p>
        <p>GIVE UP</p>
        <p>NO REST</p>
        <p>NO FREEDOM</p>
        <p>DEATH IS NO ESCAPE</p>
        <p>FEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEARFEAR FEAR FEAR FEAR FEAR</p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
